version: '3.3'

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    image: nuxt_dev
    container_name: nuxt-dev
    command: yarn dev
    volumes:
      - ./src:/app/src/
    ports:
      - '3000:3000'
